# Generated by Django 6.0.5 on 2026-05-25 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('SAP', 'SAP Fuel & Procurement'), ('UTILITY', 'Utility Electricity'), ('TRAVEL', 'Corporate Travel')], max_length=10)),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('total_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('suspicious_rows', models.IntegerField(default=0)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row_number', models.IntegerField()),
                ('source', models.CharField(max_length=10)),
                ('scope', models.CharField(choices=[('scope_1', 'Scope 1'), ('scope_2', 'Scope 2'), ('scope_3', 'Scope 3')], max_length=10)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('suspicious', 'Suspicious'), ('failed', 'Failed Validation'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('validation_errors', models.JSONField(default=list)),
                ('analysis_flags', models.JSONField(default=list)),
                ('transformations', models.JSONField(default=list)),
                ('raw_data', models.JSONField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_records', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.uploadbatch')),
            ],
        ),
    ]
