# Generated by Django 6.0.5 on 2026-05-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionrecord',
            name='emission_factor_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='emission_factor_vintage',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
