# Generated by Django 6.0.5 on 2026-05-28 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0004_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emissionrecord',
            name='emission_factor_value',
        ),
        migrations.RemoveField(
            model_name='emissionrecord',
            name='emission_factor_vintage',
        ),
    ]
